### ISSUE TITLE
build.zig:173:22: error: expected 2 arguments, found 3

### ISSUE THREAD

**Issue by Jorrdannx** [Auzgame/clumsy0.3#1]
Can you assist with this please? not quite sure why its failing the build

![image](https://github.com/Auzgame/clumsy0.3-with-keybinds/assets/39964832/ddaea489-09ca-421d-b08e-1fc3aa9c725d)

**Comment by Auzgame** [comment]
Your using the wrong zig version

**Comment by Auzgame** [comment]
Closed due to inactivity
